baseURL = "https://yizhaocannas18.github.io/yizhaocannas.github.io/"
canonifyURLs = true
languageCode = "it-IT"
defaultContentLanguage = "it"
title = "Portfolio Fotografico"
theme = "hello-friend-ng"

[params]
  # Configurazione base del tema
  showPostCoverInList = true
  showPostCoverInSingle = true

  # Personalizza il logo testuale
  [params.logo]
    logoText = "Portfolio Fotografico"
    logoHomeLink = "/"

  [params.author]
    name = "Fotografo"

[languages.it]
  title = "Portfolio Fotografico"
