backend:
  name: github
  repo: "yizhaocannas18/yizhaocannas18.github.io"
  branch: main
  base_url: https://decap-cms-github-oauth.pcarion.com

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Post Fotografici"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Copertina", name: "cover", widget: "image", required: false}
      - {label: "Corpo", name: "body", widget: "markdown", required: false}
